### ISSUE TITLE
[Enhance] Sintax Linter Correction

### ISSUE THREAD

**Issue by arcas0803** [artflutter/reactive_forms_generator#10]
Widgets constructor should be const,

`ReactiveMigrantFormConsumer({Key? key, required this.builder, this.child})
      : super(key: key);`

These 3 packages are not used by gform class:

`import 'package:reactive_forms/src/widgets/inherited_streamer.dart';
import 'dart:convert';
import 'package:reactive_forms_annotations/reactive_forms_annotations.dart';`

**Comment by vasilich6107** [comment]
@arcas0803 ignore the code for now.
Maybe lately I will address this enhancements

**Comment by arcas0803** [comment]
Is just an Enhance with low low priority.

**Comment by vasilich6107** [comment]
@arcas0803 
Fixed in 0.4.0-beta
Check the changelog https://github.com/artflutter/reactive_forms_generator/blob/master/packages/reactive_forms_generator/CHANGELOG.md

**Comment by arcas0803** [comment]
Fixed
