### ISSUE TITLE
How to declare predefined validators?

### ISSUE THREAD

**Issue by stact** [artflutter/reactive_forms_generator#13]
I follow the doc to declare static method to get requiredValidator

```dart
Map<String, dynamic>? requiredValidator(AbstractControl<dynamic> control) {
  return Validators.required(control);
}
```

but I tried to implements also other methods 
https://github.com/joanpablo/reactive_forms#predefined-validators

I've some lack of knowledge about declaring complex validators like min / max / equals / must match etc.
Do you think we could have those methods under the generated code? Otherwise could we have additional doc or resources in doc to implements those methods?

Thank you in advance for your help.

**Comment by vasilich6107** [comment]
Hi @stact 
Check the original form docs validation section
https://github.com/joanpablo/reactive_forms#what-about-validators

**Comment by vasilich6107** [comment]
@stact 
check the min validator signature
https://github.com/joanpablo/reactive_forms/blob/master/lib/src/validators/validators.dart#L69


```dart
Map<String, dynamic>? min(AbstractControl<dynamic> control) {
  return Validators.min(10)(control);
}
```

**Comment by vasilich6107** [comment]
> Do you think we could have those methods under the generated code?
No, cause those validators are not static. They have a variable parameter such as length incase of `min`

**Comment by stact** [comment]
Oh right, thx @vasilich6107 I was in a wrong way. I tried to put the value to check directly on `@FormControlAnnotation`
