### ISSUE TITLE
Make the auto-generated form class implement a minimal abstract class

### ISSUE THREAD

**Issue by BenjaminFarquhar** [artflutter/reactive_forms_generator#15]
Do you think you could make the auto-generated form implement a minimal abstract class since they all do anyway? They just don't have the `implements` keyword, which means we can't use the interface in our code:

```
abstract class FormModel<TModel> {
  FormModel({required this.form});
  final FormGroup form;
  TModel get model;
}
```
For example, I have this generated code:

`class UserCredentialForm {`

And would like it to generate this instead:

`class UserCredentialForm implements FormModel<UserCredential> {`

It would allow me to do this:
```

/// The base form view model which all other forms extend.
abstract class FormVm<TModel, TSubmitResponse> {
  FormVm({required this.$provider}) {
    $onInit();
  }

  @protected
  void $onInit() {}

  late FormModel<TModel> $formModel; // <===== see this
  late TModel $initialValue;

  @mustCallSuper
  void $onDestroy() {
    $formModel.form.markAsUntouched();// <===== here
  }
  
    Future<SuccessResult<TSubmitResponse>?> $saveMethod() async {
    return await ($formModel.model as DomainEntity).$save()// <===== here
        as Future<SuccessResult<TSubmitResponse>?>;
  }
```

**Comment by vasilich6107** [comment]
Hi @BenjaminFarquhar 
Interesting idea
I will try to experiment around that

**Comment by vasilich6107** [comment]
@BenjaminFarquhar 
I do not think that this is viable approach
as far as each `gform.dart` will have it's own `abstract class FormModel<TModel>` and they will not be interhcangable

**Comment by vasilich6107** [comment]
but maybe `abstract class FormModel<TModel> {` could b imported from annotations package...

**Comment by vasilich6107** [comment]
@BenjaminFarquhar check latest versions

**Comment by BenjaminFarquhar** [comment]
@vasilich6107 Fantastic. I have confirmed it is working for me. Thanks for implementing this so fast!

**Comment by vasilich6107** [comment]
Closing the issue for now.
Hope it will be useful for community.
Happy new year!
