### ISSUE TITLE
Remove() functions cause FormControlNotFoundException when accessing FormModel.model

### ISSUE THREAD

**Issue by BenjaminFarquhar** [artflutter/reactive_forms_generator#16]
For the scenario where you want to re-use a form model but without some fields, we have the generated `remove` functions, e.g.:

```
  void passwordRemove({bool updateParent = true, bool emitEvent = true}) =>
      form.removeControl(passwordControlPath(),
          updateParent: updateParent, emitEvent: emitEvent);
```

When you use them:

```
  void setUpForm() {
    formModel.passwordRemove();
  }
```

Then try to access `formModel.model`, you get a `FormControlNotFoundException`.

**Comment by BenjaminFarquhar** [comment]
@vasilich6107 Do you think I could take a look at this issue?

**Comment by vasilich6107** [comment]
Check latest versions on pub.dev

**Comment by BenjiFarquhar** [comment]
@vasilich6107 I think this bug has crept back in. Could we re-open? It is occurring again for me in the same code that I was initially getting this exception for.
