### ISSUE TITLE
Nested FormGroups "contains" functions return false when they should return true

### ISSUE THREAD

**Issue by BenjaminFarquhar** [artflutter/reactive_forms_generator#18]
The code below returns false when the `homeForm` does contain a control called `"city"`.

```
builder: (context, formModel, child) {
  if (formModel.homeForm.containsCity) {
    print('Issue is fixed, well done!');
  }
}
```

Test it in the `GroupContainsFormWidget`, which can be viewed in the app in the "Group contains test" menu item of the example app.

**Comment by vasilich6107** [comment]
Fixed nested `contains`
https://github.com/artflutter/reactive_forms_generator/pull/21/commits/46baef1fa61aaf9a72e816706a3f19f2cefd7af3

**Comment by vasilich6107** [comment]
Check latest versions on pub.dev
