### ISSUE TITLE
Calling the nested FormGroups' "remove" functions does not remove the nested forms' controls

### ISSUE THREAD

**Issue by BenjaminFarquhar** [artflutter/reactive_forms_generator#19]
The code below does not enter inside the if statement (didn't use "contained" as that is another bug).

```
builder: (context, formModel, child) {
  formModel.homeForm.cityRemove();
  if (formModel.homeForm.cityControl == null) {
    print('You fixed removing a nested form\'s control. Good job!');
  }
}
```
Test it in the `GroupRemoveFormWidget`, which can be viewed in the app in the "Group remove test" menu item of the example app.

**Comment by vasilich6107** [comment]
Fixed https://github.com/artflutter/reactive_forms_generator/pull/21/commits/5c0621b9452f5e89fab11c33329e2a6f1ee26218

**Comment by vasilich6107** [comment]
Check latest versions on pub.dev
