### ISSUE TITLE
Not supporting analyzer 3

### ISSUE THREAD

**Issue by stact** [artflutter/reactive_forms_generator#22]
Could we upgrade to last version of analyzer on reactive_forms_generator to prevent breaking existing dependencies please?

**Comment by stact** [comment]
Let's wait support reactive_forms 11

**Comment by vasilich6107** [comment]
RFG supports RF11 already

**Comment by stact** [comment]
Ok let's have analyzer 3 ready but I'm not sure about this upgrade working, maybe other packages used by RF ecosystem are using 2.7.0

**Comment by stact** [comment]
For eg. I can't upgrade injectable_generator

**Comment by vasilich6107** [comment]
check  reactive_forms_generator 0.8.0-beta
