### ISSUE TITLE
How to use non-const validators

### ISSUE THREAD

**Issue by BenjiFarquhar** [artflutter/reactive_forms_generator#71]
What's the best way to use a validator that takes an argument like a min or max?

the validators in the .gform file force it to be a const, so this has a compile time error:

```
      @FormControlAnnotation(
        validators: [VpValidators.minDuration(Duration(seconds: 10))],
      )
```

**Comment by efraimbart** [comment]
I'm under the impression that annotations can only have `const` constructors, and so in the words of the docs, [validators should be top level functions or static class fields](https://pub.dev/packages/reactive_forms_generator#:~:text=required(control)%3B%0A%7D-,As%20far%20as%20we%20are%20using%20annotations%20%2D%20validators%20should%20be%20top%20level%20functions%20or%20static%20class%20fields.,-Now%20we%20are).

**Comment by BenjiFarquhar** [comment]
I think you're right. It just means you can't pass the validator an argument such as a minLength of 10. So you have to create a const validator for every unique argument you want to pass in. I did that above the form definition so it doesn't pollute the common validators with the same validator just with a different param:

```
Map<String, dynamic>? atLeastTenSeconds(AbstractControl<dynamic> control) {
  return VpValidators.minDuration(const Duration(seconds: 10)).call(control);
}
...
@FormControlAnnotation(
    validators: [atLeastTenSeconds],
)
```
