### ISSUE TITLE
Calling the generated FormModel's `remove<Model>ItemAtIndex()` appears buggy.

### ISSUE THREAD

**Issue by efraimbart** [artflutter/reactive_forms_generator#75]
In the Delivery List example, calling [`removeClientListItemAtIndex()`](https://github.com/artflutter/reactive_forms_generator/blob/master/packages/reactive_forms_generator/example/lib/docs/delivery_list/delivery_list.gform.dart#L646) on any index other than the last removes the correct item from the underlying model, but the widget always displays as if the last one was removed rather than the correct one.

**Comment by ahmednfwela** [comment]
I think this looks like a key problem in flutter instead of this package

**Comment by efraimbart** [comment]
@ahmednfwela Why do you say that?

**Comment by ahmednfwela** [comment]
because this example works just fine since it provides keys https://github.com/artflutter/reactive_forms_generator/blob/master/packages/reactive_forms_generator/example/lib/docs/delivery_list/delivery_route_form.dart#L39

**Comment by efraimbart** [comment]
Perhaps it's my issue in this case, I'll try adding keys.

**Comment by efraimbart** [comment]
Providing keys dependent on indexes to list items doesn't work well when manipulating the list. I've gone with the below:

```
key: Key('$T:${item.model.id}'),
```

**Comment by ahmednfwela** [comment]
> Providing keys dependent on indexes to list items doesn't work well when manipulating the list. I've gone with the below:
> 
> ```
> key: Key('$T:${formItem.model.id}'),
> ```

yes of course ids make more sense than indixes

**Comment by abuu-u** [comment]
i don't have id, using hashCode instead, seems ok. just wanted to ask is using hashCode ok or there are other options if you don't have id, without using uuid or any form of generating id

**Comment by efraimbart** [comment]
Anything unique to the individual item should be ok.
