### ISSUE TITLE
[proposal] Make generated file as a `part` of the base file

### ISSUE THREAD

**Issue by furaiev** [artflutter/reactive_forms_generator#8]
Currently, we need to import both `base` and `generated` files:
```
import 'login.dart';
import 'login.gform.dart';
```

Let's make it as in `built_value` or `freezed` use `part / part of`.
```
// base
part 'login.gform.dart';

// generated
part of 'login.dart';
```

In this case, we can import only the `base` file.

**Comment by vasilich6107** [comment]
@furaiev 
Fixed in 0.4.0-beta
Check the changelog https://github.com/artflutter/reactive_forms_generator/blob/master/packages/reactive_forms_generator/CHANGELOG.md
