### ISSUE TITLE
get Model error

### ISSUE THREAD

**Issue by arcas0803** [artflutter/reactive_forms_generator#9]
I discover an error on the get model method.
If I use a class where not all the fields are mark as FormControlAnotation() the build runner use getters that does not exist.
Example:
`class TinyForm{
    @FormControlAnnotation() this.name,
    this.lastNameFather,
}`

Then the builder generates:

`Tiny get model => Tiny(
      name: nameValue, => this exist
      lastNameFather: lastNameFatherValue, => this does not exist. The compiler does not warm before execution because the analyzer omits the files on the config recommended
)
`

**Comment by arcas0803** [comment]
I can work perfectly with this, but is just to advice you of this issue

**Comment by vasilich6107** [comment]
@arcas0803 thanks will try to cover this case

**Comment by vasilich6107** [comment]
@arcas0803 fixed in 0.2.1-beta

**Comment by arcas0803** [comment]
I get the same problem. It generates controll names from fields that are not included by annotation and also put those fields in get Model.

**Comment by vasilich6107** [comment]
@arcas0803 as you can see here it gets the value directly from initial model

https://github.com/artflutter/reactive_forms_generator/blob/master/packages/reactive_forms_generator/example/lib/forms/login.gform.dart#L218

**Comment by vasilich6107** [comment]
@arcas0803 if you still experiencing the issue - could you add some reproduction code here

**Comment by arcas0803** [comment]
What i was looking for is that the generator doesn't write form controls for all fields of the object.
If I have a class:
`class User{
String? name;
String? password;
String? description

}
`

If I mark as FormControl:
`class User{
@FormControlAnnotation(
      
    )
         this.name,


@FormControlAnnotation(
      
    )
        this.password,
this.description,
}`

The generation should write something like:
`
static String nameControlName = "name";
static String passwordControlName = "password";
// Do not generate description controlName
`
The same for path methods, form controls builder ...
And in model, the same:

`User get model => User(
      name: nameValue,
      password: passwordValue,
);
`

**Comment by vasilich6107** [comment]
@arcas0803 it cannot omit `description` in 
```
User get model => User(
      name: nameValue,
      password: passwordValue,
);
```

cause `description` could be `required`

this is why the model should look like

```
User get model => User(
      name: nameValue,
      password: passwordValue,
      description: user.description
);
```

it just takes the `non-annotated` value from initial model;

**Comment by vasilich6107** [comment]
As you can see in this example
https://github.com/artflutter/reactive_forms_generator/blob/master/packages/reactive_forms_generator/example/lib/forms/login.gform.dart#L218

It takes `unAnnotated` item from initial `login` model.

**Comment by vasilich6107** [comment]
I will check why it is still generates `unAnnotatedControlName`

**Comment by vasilich6107** [comment]
@arcas0803 fixed redundant getters in latest version
https://pub.dev/packages/reactive_forms_generator/changelog

**Comment by vasilich6107** [comment]
@arcas0803 could you confirm that issues is fixed?

**Comment by vasilich6107** [comment]
@arcas0803 could you confirm that issues is fixed?

**Comment by arcas0803** [comment]
Solved
